location              = "eastus"
resource_group_name   = "rg-func-demo"
function_app_name     = "func-demo-dev"
app_service_plan_name = "func-demo-plan-dev"
application_insights_name = "func-demo-ai-dev"
key_vault_name        = "func-demo-kv-dev"