location              = "eastus2"
resource_group_name   = "rg-func-demo"
function_app_name     = "fa-func-demo-dev"
app_service_plan_name = "asp-func-demo-dev"
application_insights_name = "ai-func-demo-dev"
key_vault_name        = "kv-func-demo2-dev"