name: Deploy Infrastructure

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/deploy_infra.yml"
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - run: terraform -version
      
      - name: Initialize Terraform
        run: terraform init -backend-config="storage_account_name=safuncdemotfdmd" -backend-config="container_name=tfstatecontainer" -backend-config="key=demotfstate" -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP }}"

      - name: Plan Terraform
        run: terraform plan -var-file=dev.tfvars
        env:
            ARM_SUBSCRIPTION_ID: ${{ secrets.SubscriptionID }}

      - name: Apply Terraform
        run: terraform apply -auto-approve -var-file=dev.tfvars
        env:
            ARM_SUBSCRIPTION_ID: ${{ secrets.SubscriptionID }}
