name: Deploy Infrastructure

permissions:
  id-token: write
  contents: read

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/deploy_infra.yml"
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    env:
      STORAGE_ACCOUNT_NAME: "safunctfstate"
      CONTAINER_NAME: "tfstatecontainer"
      STATE_FILE_KEY: "terraform.tfstate"     
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: terraform -version
      
      - name: Initialize Terraform
        run: |
          terraform init \
            -backend-config="storage_account_name=${STORAGE_ACCOUNT_NAME}" \
            -backend-config="container_name=${CONTAINER_NAME}" \
            -backend-config="key=${STATE_FILE_KEY}" \
            -backend-config="resource_group_name=${{vars.AZURE_RESOURCE_GROUP}}" \


      - name: Plan Terraform
        run: terraform plan -var-file=dev.tfvars -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
        
      - name: Apply Terraform
        run: terraform apply -auto-approve -var-file=dev.tfvars -var="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}"
